apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: homeassistant-storage
 namespace: homeassistant
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
